allow customized deployer key

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -335,12 +335,21 @@ build-docker-compose: ## Builds docker-compose.yml
 			exit 1; \
 	fi
 	@sed -i.bak 's/<ZEROSSL_API_KEY>/$(ZEROSSL_API_KEY)/g' docker-compose.yml
-	@rm -f docker-compose.yml.bak
 	@if [ -z "$(L2_CHAIN_ID)" ]; then \
 			echo "Error: L2_CHAIN_ID variable is not set. Please provide a value."; \
 			exit 1; \
 	fi
 	@sed -i.bak 's/<l2-chain-id>/$(L2_CHAIN_ID)/g' docker-compose.yml
+	@if [ -z "$(DEPLOYER_PRIVATE_KEY)" ]; then \
+			echo "Error: DEPLOYER_PRIVATE_KEY variable is not set. Please provide a value."; \
+			exit 1; \
+	fi
+	@sed -i.bak 's/<deployer-private-key>/$(DEPLOYER_PRIVATE_KEY)/g' docker-compose.yml
+	@if [ -z "$(DEPLOYER_ADDRESS)" ]; then \
+			echo "Error: DEPLOYER_ADDRESS variable is not set. Please provide a value."; \
+			exit 1; \
+	fi
+	@sed -i.bak 's/<deployer-address>/$(DEPLOYER_ADDRESS)/g' docker-compose.yml
 	@rm -f docker-compose.yml.bak
 
 .PHONY: run-l2-explorer-json-rpc
